server:
  port: 8081
spring:
  application:
    name: avaliacao-api

  cloud:
    openfeign:
      client:
        config:
          viaCepClient:
            connectTimeout: 3000
            readTimeout: 500
            loggerLevel: BASIC

  datasource:
    url: jdbc:postgresql://postgres-avaliacao:5432/postgres
    username: admin
    password: senha123

    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

eureka:
  client:
    service-url:
      defaultZone: http://172.23.0.1:8761/eureka
