server:
  port: 8080
spring:
  application:
    name: avaliacao-api

  datasource:
    url: jdbc:mysql://localhost:3306/ethos
    username: root
    password: 56674894

    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
